version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
  - package-ecosystem: "npm"
      directory: "/packages/nrkno-test"
      schedule:
        interval: "daily"
      allow:
        - dependency-type: "production"
      open-pull-requests-limit: 30


