version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/packages/sanity-plugin-nrkno-odd-utils"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"


  - package-ecosystem: "npm"
    directory: "/packages/nrkno-sanity-typesafe-schemas"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/packages/sanity-plugin-nrkno-iframe-preview"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/packages/nrkno-iframe-preview-api"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/packages/nrkno-sanity-react-utils"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"


  - package-ecosystem: "npm"
    directory: "/packages/sanity-plugin-nrkno-schema-structure"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/packages/sanity-plugin-nrkno-spellcheck"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

